// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJG9JXqAGWz2XQ1Mmswi9YTX6efOw53Xo',
    appId: '1:1083970971819:android:2940b0195485c416e5efee',
    messagingSenderId: '1083970971819',
    projectId: 'restaurantapp-2a43d',
    storageBucket: 'restaurantapp-2a43d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALegH2yH-If8_Gkshob13fKzdHjQ4oxuc',
    appId: '1:1083970971819:ios:a1c7ebbc2c43402de5efee',
    messagingSenderId: '1083970971819',
    projectId: 'restaurantapp-2a43d',
    storageBucket: 'restaurantapp-2a43d.appspot.com',
    androidClientId: '1083970971819-oenp28p9l9ko9qto4u44nqa15tq4u47i.apps.googleusercontent.com',
    iosClientId: '1083970971819-tbi7vokj7rg6a2u9e07ri6448pn2mvil.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );
}
